// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SRD_SkipTitleScreen","status":true,"description":"Skips the Title Screen!\r\nPretty cool, right?","parameters":{}},
{"name":"DisableMouse","status":true,"description":"Disables mouse clicks.","parameters":{}},
{"name":"Foreground","status":true,"description":"display foreground tiling sprite","parameters":{}},
{"name":"TitleCommandPosition","status":false,"description":"Changes the position of the title command window.","parameters":{"Offset X":"-200","Offset Y":"-50","Width":"240","Background":"0"}},
{"name":"Fullscreen","status":false,"description":"Starts the game in fullscreen","parameters":{}}
];
